Prepare null value handling in aggregators [WIP Do not merge]
pi-r-p/warp10-platform pull request #1
Opened 2022-10-21 15:45 UTC by randomboolean

This PR is a proposition.
We defer the conversions of locations and elevations from GTSHelper to MACROMAPPER.

This prepare the ground for:
1. A sub COW GTS structure that will hold the subarrays instead of an array of sublists
2. Replace WarpScriptAggregatorOnSubLists into WarpScriptAggregatorOnSubGTS
3. GTSHelper will create a sub COW GTS if it sees a WarpScriptAggregatorOnSubGTS -> fringe case will now be handled by the apply method of the aggregator instead of having to be implicit between GTSHelper and MACROMAPPER (and all subsequent functions that will use it)
4. Proposition: WarpScriptAggregatorFunction extends WarpScriptAggregatorOnSubGTS with a default method implementation to guarantee backward support (applyOnSubGts will fall back to apply) -> every new function will only have to implement applyOnSubGts
5. We can then remove the case in GTSHelper.bucketize when it sees a WarpScriptAggregatorFunction
6. In a next PR, null handling functions will only need to wrap WarpScriptAggregatorOnSubGTS, to effectively alter the COW lists contained in the sub GTS prior to apply -> same goes for STRICTMAPPER and any other function taking an aggregator as argument

2022-10-26 08:33 UTC, pi-r-p requested changes

2022-10-26 08:33 UTC, pi-r-p commented on warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
>            }
We understand why this is Doube.NaN instead of NO_LOCATION later in MACROMAPPER. It should be simpler to put null here and to create the constant list in MACROMAPPER. 
null is better for aggregators that do not care about position and elevation, you do not create the constant list object.

2022-10-26 08:33 UTC, pi-r-p commented on warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
> +            parms[5] = new ReadOnlyConstantList(count, Double.NaN);
same remark

2022-10-26 08:33 UTC, pi-r-p commented on warp10/src/main/java/io/warp10/script/WarpScriptAggregatorOnListsFunction.java
> +  public Object applyOnSubLists(Object[] subLists) throws WarpScriptException;
please update the comment. This is no more a list ready to push on the stack. You can explain here what should be expected in parms[4] and parms[5]. I really think null is better than testing instanceof COWList.

2022-10-26 15:32 UTC, randomboolean commented on warp10/src/main/java/io/warp10/script/WarpScriptAggregatorOnListsFunction.java
> +  public Object applyOnSubLists(Object[] subLists) throws WarpScriptException;
I modified it but the comment will be obsolete when we will use WarpScriptAggregatorOnSubGts

2022-10-28 14:34 UTC, pi-r-p approved these changes

2022-10-28 14:35 UTC, merged